import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import '../globals.css'

import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { ClerkProvider } from '@clerk/nextjs'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'VUTTR | Very Useful Tools to Remember',
  description: 'Generated by NextJs',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params

  if (!routing.locales.includes(locale as any)) {
    notFound()
  }

  const messages = await getMessages()

  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={cn(
          'h-screen w-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ClerkProvider>
          <NextIntlClientProvider messages={messages}>
            <main className="relative size-full flex-1">{children}</main>
            <Toaster />
          </NextIntlClientProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
